### ISSUE TITLE
Update Documentation for TYPO3 >= 7

### ISSUE THREAD

**Issue by h3nn3s** [teaminmedias-pluswerk/ke_search_hooks#1]
Hi all,

I recently added a couple of own indexers to my extensions.
This worked perfectly nice in the past.

Recently I discovered some problems with TYPO3 7 LTS - The fields "sysfolder" and "startingpoints_recursive" are not displayed in Backend. The TCA-Addition in the hook looks good for me.

After debugging for hours today I found the Issue(s). The documentation is outdated, this Example-Extension also did not get adopted to 7.

Overriding TCA should now be done within Configuration/TCA/Overrides/tx_kesearch_indexerconfig.php.

When dealing with field startingpoints_recursive you also need a small method to get pidlist recursively within your hook, e.g:
`
	public function getPidList($startingPointsRecursive = '', $singlePages = '') {

		$this->queryGen = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Database\\QueryGenerator');
		$pidsRecursive = \TYPO3\CMS\Core\Utility\GeneralUtility::trimExplode(',', $startingPointsRecursive, true);
		$pidsNonRecursive = \TYPO3\CMS\Core\Utility\GeneralUtility::trimExplode(',', $singlePages, true);
		foreach($pidsRecursive as $pid) {
			$pageList .= $this->queryGen->getTreeList($pid, 99, 0, '1=1') . ',';
		}
		foreach($pidsNonRecursive as $pid) {
			$pageList .= $pid . ',';
		}
		return \TYPO3\CMS\Core\Utility\GeneralUtility::trimExplode(',', $pageList, true);
	}
`

**Comment by h3nn3s** [comment]
I added a Gist from my CustomIndexer: [class.user_kesearchhooks.php](https://gist.github.com/h3nn3s/6df3d951dbed596d9fd1a1361700301e)

**Comment by christianbltr** [comment]
Hi, could you create a pull request that issue?

**Comment by h3nn3s** [comment]
Done. 
Sorry for late response - the last weeks were very busy.

**Comment by christianbltr** [comment]
Please see comment in https://github.com/teaminmedias-pluswerk/ke_search_hooks/pull/2
