### ISSUE TITLE
Too few arguments to function

### ISSUE THREAD

**Issue by Teisi** [teaminmedias-pluswerk/ke_search_hooks#13]
TYPO3 | 9.5.15
ke_search | 3.1.6
ke_search_hooks | 3.1.0

After install ke_search_hooks: BE -> go to list-modul -> try to add new Indexer -> ERROR

"Too few arguments to function TeaminmediasPluswerk\KeSearch\Indexer\IndexerBase::__construct(), 0 passed in .../typo3_src-9.5.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3681 and exactly 1 expected"

**Comment by christianbltr** [comment]
Could you try using the master version of ke_search_hooks? There are some changes in how the custom indexers have to be called, those aren't yet released as a new version, see
https://github.com/teaminmedias-pluswerk/ke_search_hooks/blob/master/ChangeLog

**Comment by Elpiojo83** [comment]
Had the same issue in master today.

**Comment by christianbltr** [comment]
Fixed in ke_search master, will be in version 3.1.7.
