### ISSUE TITLE
Own Url on custom indexer

### ISSUE THREAD

**Issue by weltreisendertj** [teaminmedias-pluswerk/ke_search_hooks#15]
I´m using a custom indexer. It´s using the $params = '&slug='. $record['slug']. '&tx_..._...key[action]=show'; to generate the url.
But I like to put here my own url for seo reasons.
Currently the links will be generated in typo format with cHash and so one this will result in duplicate content results for google :-(.
Do you have an idea how I can put here my own links (starting from https://...)

**Comment by christianbltr** [comment]
Normally it shouldn`t be necessary to add a slug in the parameters. You should rather configure the routing in the site configuration for that parameters as described in 
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Routing/AdvancedRoutingConfiguration.html
