### ISSUE TITLE
Add example for custom filter renderer

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search_hooks#3]
A hook in ke_search allows you to implement your own custom filter render. 

You can for example add a filter which depends on another filter.

It would be good to have an example like in the older version of ke_search_hooks.

**Comment by sommerhit76** [comment]
This is an old issue, but I'd be very interested in such an example. I'm trying to get this to run, but so far without any luck – not sure what the method `customFilterRenderer()` should return...

**Comment by christianbltr** [comment]
see https://github.com/tpwd/ke_search_hooks/commit/8f476400cd49e903956242be44ea76a2050c17bf
