### ISSUE TITLE
Add example for adding custom information in the result list

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search_hooks#4]
Adding your own information in the result list is possible with fluid (for example using a view helper) and there are also some hooks for that.

It would be good to have an example for that in ke_search_hooks

**Comment by izaquieltome** [comment]
this would still be a nice addition - as I am trying to figure out how to do this cause I really need this for a project.

**Comment by christianbltr** [comment]
see https://github.com/tpwd/ke_search_hooks/issues/2
