### ISSUE TITLE
Update extension for TYPO3 v9

### ISSUE THREAD

**Issue by sommerhit76** [teaminmedias-pluswerk/ke_search_hooks#5]
Please make extension compatible with TYPO3 v9, thanks!

**Comment by rowild** [comment]
Added PR to update the query using the new Doctrine DBAL features via the ConnectionPool class.

Further ideas for "modernisation"?

Using uriBuilder to create the link to the detail view would be one idea. uriBuilder would save the cHash, too, but that might not be desired for a search indexer (here I have toooooo little experience and knowledge).

**Comment by christianbltr** [comment]
Just merged the PR
